sudo: required
services:
  - docker
dist: focal
before_install:
  - rvm reinstall ruby-3.3.5 || true
  - gem uninstall nokogiri -aIx || true
  - gem install nokogiri --platform=ruby -- --use-system-libraries
  - docker build -t ais777/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ais777/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-047719613436"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"