# Tell Travis we need a copy of docker running
sudo: required
services:
  - docker

# Build our image using Dockerfile.dev
before_install:
  - docker build -t ais777/docker-react -f Dockerfile.dev .

# Tell Travis how to run our test suite
script:
  - docker run -e CI=true ais777/docker-react npm run test